name: test-actions

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+' ]

jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        steps:
        - name: Get the version
          id: get_version
          run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          
        - name: Set image name
          id: set_image
          run: echo ::set-output name=IMAGE_NAME::gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}:${{ steps.get_version.outputs.VERSION }}
        
        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . -t ${{ steps.set_image.outputs.IMAGE_NAME }}

        - name: Push Docker image
          run: docker push ${{ steps.set_image.outputs.IMAGE_NAME }}

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image ${{ steps.set_image.outputs.IMAGE_NAME }} --region us-central1 --platform managed --timeout "2m" --port 8000     
